# Generated by Django 5.2.3 on 2025-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date_of_birth'),
        ('patients', '0002_patient_is_approved_patient_is_blocked'),
    ]

    operations = [
    ]
