# Generated by Django 5.2.3 on 2025-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General', 'General'), ('Lungs Specialist', 'Lungs Specialist'), ('Dentist', 'Dentist'), ('Psychiatrist', 'Psychiatrist'), ('Covid-19', 'Covid-19'), ('Surgeon', 'Surgeon'), ('Cardiologist', 'Cardiologist')], max_length=100),
        ),
    ]
