# Generated by Django 5.2.3 on 2025-06-12 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
