# Generated by Django 5.2.3 on 2025-06-14 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_patient_age_remove_patient_allergies_and_more'),
        ('patients', '0002_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
