# Generated by Django 5.2.3 on 2025-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_is_approved_doctor_is_blocked'),
        ('doctor', '0007_alter_appointment_patient_delete_patient'),
    ]

    operations = [
    ]
